DROP TABLE IF EXISTS FILMS;

CREATE TABLE FILMS(
    ID  INT PRIMARY KEY NOT NULL,
    TITLE   TEXT    NOT NULL,
    ORIGINAL_TITLE  TEXT    NOT NULL,
    COUNTRIES   TEXT    NOT NULL,
    RELEASE_DATE    TEXT    NOT NULL,
    DIRECTOR    TEXT    NOT NULL,
    GENRES  TEXT    NOT NULL
);